const TRANSACTION_CATEGORIES = [
  'FOOD_AND_DRINK',
  'TRANSPORTATION',
  'TRAVEL',
  'SHOPPING',
  'ENTERTAINMENT',
  'PERSONAL_CARE',
  'HEALTH_AND_FITNESS',
  'EDUCATION',
  'GENERAL_MERCHANDISE',
  'HOME_IMPROVEMENT',
  'RENT_AND_UTILITIES',
  'GENERAL_SERVICES',
  'GOVERNMENT_AND_NON_PROFIT',
  'BANK_FEES',
  'TRANSFER_IN',
  'TRANSFER_OUT',
  'LOAN_PAYMENTS',
  'INCOME',
] as const;

export { TRANSACTION_CATEGORIES };
