import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@/assets/styles/globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/** TODO!
 * - Create shared header and footer component
 * - Add login/register <Link> button: https://nextjs.org/docs/app/api-reference/components/link
 *   - Routes to /login
 *   - Routes to /register
 * - Create <ThemeProvider> to inject themes: https://nextjs.org/docs/app/getting-started/server-and-client-components#context-providers
 * - client componenets vs server components ie 'use client': https://react.dev/reference/rsc/use-client
 */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
