const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  NOT_FOUND: 'NOT_FOUND',
  PLAID_ERROR: 'PLAID_ERROR',
  DEMO_RESTRICTED: 'DEMO_RESTRICTED',
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  FEATURE_FLAG_CACHE_ERROR: 'FEATURE_FLAG_CACHE_ERROR',
  SERVER_ERROR: 'SERVER_ERROR',
} as const;

type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export { ERROR_CODES, type ErrorCode };
