const TRANSACTION_CATEGORIES = {
  FOOD_AND_DRINK: 'FOOD_AND_DRINK',
  TRANSPORTATION: 'TRANSPORTATION',
  TRAVEL: 'TRAVEL',
  SHOPPING: 'SHOPPING',
  ENTERTAINMENT: 'ENTERTAINMENT',
  PERSONAL_CARE: 'PERSONAL_CARE',
  HEALTH_AND_FITNESS: 'HEALTH_AND_FITNESS',
  EDUCATION: 'EDUCATION',
  GENERAL_MERCHANDISE: 'GENERAL_MERCHANDISE',
  HOME_IMPROVEMENT: 'HOME_IMPROVEMENT',
  RENT_AND_UTILITIES: 'RENT_AND_UTILITIES',
  GENERAL_SERVICES: 'GENERAL_SERVICES',
  GOVERNMENT_AND_NON_PROFIT: 'GOVERNMENT_AND_NON_PROFIT',
  BANK_FEES: 'BANK_FEES',
  TRANSFER_IN: 'TRANSFER_IN',
  TRANSFER_OUT: 'TRANSFER_OUT',
  LOAN_PAYMENTS: 'LOAN_PAYMENTS',
  INCOME: 'INCOME',
} as const;

type TransactionCategory = (typeof TRANSACTION_CATEGORIES)[keyof typeof TRANSACTION_CATEGORIES];

const TRANSACTION_CATEGORY_LIST = Object.values(TRANSACTION_CATEGORIES);

export { TRANSACTION_CATEGORIES, TRANSACTION_CATEGORY_LIST, type TransactionCategory };
